### ISSUE TITLE
What format is the dump in?

### ISSUE THREAD

**Issue by robdejonge** [RhetTbull/macnotesapp#43]
Sorry to be posting a question as an issue, but it is not entirely clear from the website or repo in what format data would be saved is using the 'dump' command for this tool. 

I'm looking for a method to 'export' all my Notes every day for safe keeping, 'just in case' I lose access to my account and devices for whatever reason. Your tool seems promising!

**Comment by RhetTbull** [comment]
It's not in any particulary format. The dump command is currently really just a debugging command, not an archival format. I do plan to add an export command eventually (#23) but this project is lower priority for me at the moment as I'm working several other tings. Here's a sample of the dump output:

```
note.id=x-coredata://54B4394A-B836-4679-A0FB-32D4704D0E15/IMAPNote/p12
note.name=Foo
note.folder=Notes
note.account=Google
note.creation_date=2022-12-04 19:19:55
note.modification_date=2022-12-04 19:19:58
note.password_protected=False
note.body=<html><head></head><body style="overflow-wrap: break-word; -webkit-nbsp-mode: space; line-break: after-white-space;">Foo<div>Bar</div><div><br></div></body></html>

note.plaintext=Foo
Bar
```

**Comment by robdejonge** [comment]
Thanks, I appreciate you taking the time to clarify.
