### ISSUE TITLE
Proposal: Add a home-brew tap to allow installing macnotesapp

### ISSUE THREAD

**Issue by brianm** [RhetTbull/macnotesapp#49]
Given that notes works well as a command line tool, the redirect through pipx to install the end application on macOS would be nice to avoid. I'd like to propose hosting an in-repo home-brew tap with a formula for the most recent release. Basically, add a `homebrew` directory with a `notes.rb` formula in it, allowing users to `brew tap https://github.com/RhetTbull/macnotesapp/homebrew && brew update && brew install notes` and then get updates via normal `brew update`.

Happy to implement this myself, but wanted to ask about interest before I do!

**Comment by brianm** [comment]
Actually, I'll need to verify that subdirectory based taps work, but I *think* they do :-) If not, I don't want to impose keeping a different project in sync.

**Comment by RhetTbull** [comment]
Good idea. Happy to merge a PR but I don't know how to do this myself and don't have time to learn at the moment.

**Comment by brianm** [comment]
Started a PR for this. Question -- how do you make a release? I am guessing create tag and then run build.sh with the tag checked out?

To use same-repo tap, the convention will need to me that the formula in `main` is the most recent stable release. In order to make that happen as easily reliably as possible, I am not sure the best way to fit it into your workflow!

**Comment by RhetTbull** [comment]
I use [bump2version](https://pypi.org/project/bump2version/) to bump the version, run `build.sh` then use the GitHub command line client to create the relesae (`gh release create VERSION`).  It's not very automated but I don't release often. So if you need the .rb script to be updated I would do it in `build.sh` so it's included in the release.  See [RELEASE_DEV.md](https://github.com/RhetTbull/macnotesapp/blob/main/README_DEV.md) which has my "developer notes to myself" on the build process.

**Comment by brianm** [comment]
Perfect, thanks!

**Comment by RhetTbull** [comment]
Merged! Thanks for implementing this. On my system the startup time for the CLI seems to be much slower than the via pipx but brew install may be preferable for many users.

**Comment by brianm** [comment]
I'm happy to switch it over to normal python script -- maybe for the next release :-)
